CREATE TABLE "factories" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"address" text NOT NULL,
	"map_link" text,
	"contact_name" text,
	"contact_position" text,
	"contact_email" text,
	"contact_phone" text,
	"current_products" text,
	"employee_count" text,
	"shifts_per_day" text,
	"working_days" text,
	"kashrut" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "inspections" (
	"id" serial PRIMARY KEY NOT NULL,
	"factory_name" text NOT NULL,
	"inspector" text NOT NULL,
	"factory_address" text NOT NULL,
	"map_link" text,
	"hebrew_date" text,
	"gregorian_date" text NOT NULL,
	"contact_name" text,
	"contact_position" text,
	"contact_email" text,
	"contact_phone" text,
	"current_products" text,
	"employee_count" integer,
	"shifts_per_day" integer,
	"working_days" integer,
	"kashrut" text,
	"documents" jsonb,
	"document_files" jsonb DEFAULT '{}'::jsonb,
	"category" text,
	"ingredients" text,
	"boiler_details" text,
	"cleaning_protocols" text,
	"bishu_yisrael" boolean DEFAULT false,
	"afiya_yisrael" boolean DEFAULT false,
	"chalav_yisrael" boolean DEFAULT false,
	"linat_laila" boolean DEFAULT false,
	"kavush" boolean DEFAULT false,
	"chadash" boolean DEFAULT false,
	"hafrash_challa" boolean DEFAULT false,
	"kashrut_pesach" boolean DEFAULT false,
	"photos" text[] DEFAULT '{}',
	"attachments" text[] DEFAULT '{}',
	"summary" text,
	"recommendations" text,
	"inspector_opinion" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
